### ISSUE TITLE
[BLOCKING] cannot build iOS application

### ISSUE THREAD

**Issue by AndrewDongminYoo** [AndrewDongminYoo/react-native-step-counter#1]
## Expected Behavior

- Xcode 에디터 상에서는 인스펙터에 걸리는 부분이 없지만 빌드 시에 Objective-C 타입 에러가 발생

## Actual Behavior

- Error Log looks like...

  ❌. @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:45:48:
      expected a type
  
     ```c++
      - (NSDictionary *)dictionaryFromPedometerData:(CMPedometerData *)data {
                   ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:17:30:
      use of undeclared identifier 'CMPedometer'
  
     ```c++
      @"supported": @([CMPedometer isStepCountingAvailable]),
                          ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:28:11:
      property 'pedometer' not found on object of type 'RNStepCounter *'
  
     ```c++
      [self.pedometer queryPedometerDataFromDate:startDate
                ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:30:50:
      type-id cannot have a name
  
     ```c++
            withHandler:^(CMPedometerData *pedometerData, NSError *error) {
                                                                    ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:30:66:
      expected ')'
  
     ```c++
      withHandler:^(CMPedometerData *pedometerData, NSError*error) {
                                    ^~~~~~~~~~~~~~~
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:30:48:
      C++ requires a type specifier for all declarations
  
     ```c++
      withHandler:^(CMPedometerData *pedometerData, NSError *error) {
                   ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:31:53:
      use of undeclared identifier 'pedometerData'
  
     ```c++
      handler(@[[self dictionaryFromPedometerData:pedometerData]]);
                                             ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:36:11:
      property 'pedometer' not found on object of type 'RNStepCounter *'
  
     ```c++
      [self.pedometer startPedometerUpdatesFromDate:[[NSDate date]init]
             ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:37:53:
      type-id cannot have a name
  
     ```c++
       withHandler:^(CMPedometerData *pedometerData, NSError *error) {
                                     ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:37:69:
      expected ')'
  
     ```c++
       withHandler:^(CMPedometerData *pedometerData, NSError *error) {
                                                              ^~~~~~~~~~~~~~~
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:37:51:
      C++ requires a type specifier for all declarations
  
     ```c++
       withHandler:^(CMPedometerData *pedometerData, NSError *error) {
                    ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:38:13:
      use of undeclared identifier 'pedometerData'
  
     ```c++
          if (pedometerData) {
                 ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:39:19:
      no visible @interface for 'RNStepCounter' declares the selector 'sendEventWithName:body:'
  
     ```c++
       [self sendEventWithName:@"StepCounter.stepCounterUpdate"
                   ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:55:54:
      property 'startDate' not found on object of type '__strong id'
  
     ```c++
          @"startDate": [formatter stringFromDate:data.startDate]?:[NSNull null],
               ~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:56:52:
      property 'endDate' not found on object of type '__strong id'
  
     ```c++
          @"endDate": [formatter stringFromDate:data.endDate]?:[NSNull null],
                                                       ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:57:24:
      property 'numberOfSteps' not found on object of type '__strong id'
  
     ```c++
          @"steps": data.numberOfSteps?:[NSNull null],
                            ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:58:27:
      property 'distance' not found on object of type '__strong id'
  
     ```c++
          @"distance": data.distance?:[NSNull null],
                         ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:60:33:
      property 'floorsAscended' not found on object of type '__strong id'
  
     ```c++
          @"floorsAscended": data.floorsAscended?:[NSNull null],
                            ^
     ```
  
  ❌  @dongminyu/react-native-step-counter/ios/RNStepCounter.mm:61:34:
      property 'floorsDescended' not found on object of type '__strong id'
  
     ```c++
          @"floorsDescended": data.floorsDescended?:[NSNull null],
                                  ^
     ```

## Steps to Reproduce the Problem

  1. yarn add @dongminyu/react-native-step-counter
  2. ...
  3. `npx react-native run-ios --configuration Release`

## Specifications

> you shold use this command.
> ```sh
> npx react-native info
> ```

- INFO OUTPUT
```yaml
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 13.90 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.1/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.1/bin/npm
    Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - ~/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: Electric Eel 2022.1.1 Patch 1 Electric Eel 2022.1.1 Patch 1
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.3 => 0.71.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
