### ISSUE TITLE
We need detailed documentation to persuade others.

### ISSUE THREAD

**Issue by AndrewDongminYoo** [AndrewDongminYoo/react-native-step-counter#10]
## Expected Behavior

- As the new architecture's reactive native development method has clear advantages, it is also important to write meticulous documents to persuade established developers.

## Actual Behavior

- The NPM package installation script and code used in actual apps account for most of the documented content, so there is no real reference, and the corresponding existing development method is not convincing even though the risk of applying the new architecture is applied.

## Steps to Reproduce the Problem

1. `yarn add @dongminyu/react-native-step-counter`
3. `RCT_NEW_ARCH_ENABLED=1 \ cd ios && pod install`
4. `yarn run-*android/ios*`

## Specifications

> first, you should check your `react-native-step-counter` version and write it down.

- @dongminyu/react-native-step-counter version: 0.1.9

> second, you should check your `react-native` version and write it down. you should use this command. `npx react-native info`
> and then, it would be better if you paste the output of this command.

- INFO OUTPUT

```yaml
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 2.67 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.1/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.1/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    Ruby: ruby 2.7.6p219 (2022-04-12) [arm64-darwin22]
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: Electric Eel 2022.1.1 Patch 1 Electric Eel 2022.1.1 Patch 1
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
