### ISSUE TITLE
jlink executable /Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin/jlink does not exist

### ISSUE THREAD

**Issue by vanntrong** [AndrewDongminYoo/react-native-step-counter#33]
# React Native Step Counter New Issue

## Expected Behavior

- I am trying to build with this library.

## Actual Behavior

- I am getting the following error:

```log
Execution failed for task ':dongminyu_react-native-step-counter:compileReleaseJavaWithJavac'.
> Could not resolve all files for configuration ':dongminyu_react-native-step-counter:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /Users/vantrong/Library/Android/sdk/platforms/android-33/core-for-system-modules.jar.
         > jlink executable /Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin/jlink does not exist.

```

## Steps to Reproduce the Problem

1. `yarn create react-native-app my-app`
2. `yarn add @dongminyu/react-native-step-counter`
3. `react-native link @dongminyu/react-native-step-counter`
4. `npx pod-install`
5. `npx react-native run-*android/ios*`

## Specifications

> first, you should check your `react-native-step-counter` version and write it down.

- @dongminyu/react-native-step-counter version: 1.0.0

> second, you should check your `react-native` version and write it down. you should use this command. `npx react-native info`
> and then, it would be better if you paste the output of this command.

- INFO OUTPUT

```yaml
System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1
  Memory: 91.25 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.18.0
    path: ~/.nvm/versions/node/v16.18.0/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v16.18.0/bin/npm
  Watchman:
    version: 2023.09.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/vantrong/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9123335
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/vantrong/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
