### ISSUE TITLE
The package '@dongminyu/react-native-step-counter' doesn't seem to be linked

### ISSUE THREAD

**Issue by morricedev** [AndrewDongminYoo/react-native-step-counter#35]
# React Native Step Counter New Issue

## Expected Behavior

- i am trying to build with this library.
-  newArchEnabled = true it work normally
- i already tried the solution from [PR#29](https://github.com/AndrewDongminYoo/react-native-step-counter/issues/29), but without success

## Actual Behavior

- I am getting the following error:

```log
The package '@dongminyu/react-native-step-counter' doesn't seem to be linked. Make sure:

- You have the Android development environment set up: `https://reactnative.dev/docs/environment-setup.`
- Use the "npx react-native clean" command to clean up the module\'s cache and select the "watchman", "yarn", "metro", "android", "npm" options with comma-separated. Re-Install packages and re-build the app again .
- You rebuilt the app after installing the package
- You are not using Expo Go

If none of these fix the issue, please open an issue on the Github repository: https://github.com/AndrewDongminYoo/react-native-step-counter

```

## Steps to Reproduce the Problem

1. `yarn create react-native-app my-app`
2. `yarn add @dongminyu/react-native-step-counter`
3. go to node_modules/@dongminyu/react-native-step-counter/android/build.gradle and change all `compileOptions` from version `1_8` to `11`
4. in the same file, remove the toolchain, as described in this [PR](https://github.com/AndrewDongminYoo/react-native-step-counter/pull/34/files)
5. setup the package at any screen
4. `npx react-native run-android`
6. access the screen and get the error

## Specifications

- @dongminyu/react-native-step-counter version: ^0.2.1

- INFO OUTPUT

```yaml
System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1
  Memory: 97.28 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.17.1
    path: ~/.nvm/versions/node/v16.17.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/bemobile/mobile/fique-bem/apps/mobile/node_modules/.bin/yarn
  npm:
    version: 8.15.0
    path: ~/.nvm/versions/node/v16.17.1/bin/npm
  Watchman:
    version: 2023.07.03.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 28.0.3
      - 30.0.3
      - 31.0.0
      - 33.0.0
    System Images:
      - android-30 | Google Play ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9014738
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.16
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
