### ISSUE TITLE
"compileDebugKotlin" Error when trying to build for android

### ISSUE THREAD

**Issue by aykutmehmetd** [AndrewDongminYoo/react-native-step-counter#47]
# React Native Step Counter New Issue

## Expected Behavior

- I am trying to build with this library.

## Actual Behavior

- I am getting the following error:

```log
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':dongminyu_react-native-step-counter:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
```

## Steps to Reproduce the Problem

1. `npx create-expo-app my-app --template tabs@50`
2. `npx expo install @dongminyu/react-native-step-counter`
3. `eas init`
4. `Create eas.json:`
```yaml
{
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {}
  }
}
```
5. `app.json:`
```yaml
{
  "expo": {
    "android": {
      "permissions": [
        "android.permission.ACTIVITY_RECOGNITION",
        "android.permission.BODY_SENSORS_BACKGROUND"
      ],
    },
    "plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "newArchEnabled": true,
          }
        }
      ]
    ],
  }
}
```
6. `eas build -e development -p android`

## Specifications

> first, you should check your `react-native-step-counter` version and write it down.

- @dongminyu/react-native-step-counter version: 0.2.5

> second, you should check your `react-native` version and write it down. you should use this command. `npx react-native info`
> and then, it would be better if you paste the output of this command.

- INFO OUTPUT

```yaml

System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M1
  Memory: 79.73 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 9.8.1
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: javac 17
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

```
