### ISSUE TITLE
[BLOCKING] you've explicitly synthesized the RCTCallableJSModules

### ISSUE THREAD

**Issue by AndrewDongminYoo** [AndrewDongminYoo/react-native-step-counter#6]
## Expected Behavior

- I am trying to build iOS application

## Actual Behavior

- I am getting the following error:

```log
terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: StepCounter.stepCounterUpdate with body: {
    counterType = CMPedometer;
    distance = "7.899999999906868";
    endDate = "2023-03-06T07:58:16.999Z";
    floorsAscended = 0;
    floorsDescended = 0;
    startDate = "2023-03-06T07:57:57.589Z";
    steps = 10;
}. `RCTCallableJSModules` is not set. This is probably because you've explicitly synthesized the `RCTCallableJSModules` in `RNStepCounter`, even though it's inherited from `RCTEventEmitter.`'
```

## Steps to Reproduce the Problem

1. `yarn create react-native-app my-app`
2. `yarn add @dongminyu/react-native-step-counter`
3. `react-native link @dongminyu/react-native-step-counter`
4. `npx pod-install`
5. `npx react-native run-*android/ios*`

## Specifications

> first, you should check your `react-native-step-counter` version and write it down.

- @dongminyu/react-native-step-counter version: 0.1.6

> second, you should check your `react-native` version and write it down. you should use this command. `npx react-native info`
> and then, it would be better if you paste the output of this command.

- INFO OUTPUT

```yaml
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.52 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.1/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.1/bin/npm
    Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/dongminyu/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: Electric Eel 2022.1.1 Patch 1 Electric Eel 2022.1.1 Patch 1
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
